name: zoom-drive-connector
channels:
  - conda-forge
dependencies:
  - python=3.6
  - google-api-python-client=1.6.7
  - oauth2client=4.1.2
  - slackclient=1.2.1
  - pyjwt==1.5.3
  - pytest=3.10.0 # Dev dependency.
  - mypy=0.641  # Dev dependency.
  - pycodestyle=2.4.0 # Dev dependency.
  - pylint=1.9.2 # Dev dependency.
  - pip:
      - pyyaml==4.2b1
      - responses==0.10.2 # Dev dependency.
      - schedule==0.5.0
      - httplib2shim==0.0.3
